### PR TITLE
Add microdata to location

### PR DESCRIPTION
**Pull request by CMSworker**
...as suggested in #12.

### CODE REVIEW

**Comment by CMSworker** [comment]
Should changes like this be made to the master or develop branch?

**Comment by leofeyer** [comment]
No, the `develop` branch is fine. Why did you add the additional `<span>` tag?

**Comment by CMSworker** [comment]
The span is added because of the required hierarchy in the microdata format. The location name has to be a child element of the "location wrapper". The address details (street, city...) also require an additional "wrapper", when they are used (and at least the city should be added to get the events listed in Google rich snippets).

Please also see the examples at the end of the definition page at [schema.org/Event](http://schema.org/Event). Here a complete (simplified) example, with text indent for better readability:
```
<div itemscope itemtype="http://schema.org/Event">
  <h1 itemprop="name">Contao Konferenz 2017</h1>
  <p itemprop="startDate" content="2017-07-15T09:00">Thu Jul 15</p>
  <p itemprop="location" itemscope itemtype="http://schema.org/Place">
    <span itemprop="name">Seminaris SeeHotel</span>,
    <span itemprop="address" itemscope itemtype="http://schema.org/PostalAddress">
      <span itemprop="streetAddress">An der Pirschheide 40</span>,
      <span itemprop="postalCode">14471</span>
      <span itemprop="addressLocality">Potsdam</span>
    </span>
  </p>
</div>
```
You can copy this example code and paste it at the [microdata testing tool](https://search.google.com/structured-data/testing-tool) to validate it.

**addressLocality** is an itemprop of the itemscope **PostalAddress** , which is itemprop **address** of the itemscope **Place**, which is itemprop **location** of the itemscope **Event**...

**Comment by leofeyer** [comment]
The "location" field in the events module can be anything (a name, an address, a description etc.), therefore we should not assume that it always is a location name. I'm ok with adding `itemprop="location" itemscope itemtype="http://schema.org/Place"` but anything beyond seems to specific in this case.

**Comment by leofeyer** [comment]
Ad discussed in Mumble on October 5th, we want to add `itemprop="location" itemscope itemtype="http://schema.org/Place"` without `<span itemprop="name">`. Also, @ausi noted that `Place` has no `name` attribute according to the specifications: http://schema.org/Place

**Comment by CMSworker** [comment]
Thanks for the feedback. I'm sorry but I have to disagree for several reasons and I hope I can explain, why the suggested way isn't a good solution:

First:
**_Place_** is a _more specific type_ of _**Thing**_ (see the list at the end of the page [http://schema.org/Thing](http://schema.org/Thing)) and **_Name_** is a _property_ to describe a _**Thing**_, see [http://schema.org/name](http://schema.org/name). So **_name_** is also a valid _property_ to describe a **_Place_**, because a **_Place_** is a **_Thing_**.

Second:
Have a look at the many examples at the end of the page [http://schema.org/Place](http://schema.org/Place) - in **all examples** on this page the **_name_** is set as a _propery_ of **_Place_**. And I really mean **all examples**, no matter if you see the examples for microdata, RDFa or JSON-LD.

Third:
`<span>` is the common way to add the **name** _property_ when using **microdata** - again, please have a look at all the examples on the end of the page [http://schema.org/Place](http://schema.org/Place). The main reason is because it has to be a **child element** of the **Place** _itemtype_. **Microdata** has to be inserted directly to html elements. If you don't want to add additional html elements you shouldn't use **microdata** but **JSON-LD** instead. Contao is currently not prepared for JSON-LD and there's only microdata used everywhere by now, so we should keep on using the microdata implementation and markup.

Fourth:
The general reason to add microdata is to make the content accessible for machines, so that they can understand the content and interpret the text presented on the page.  An "empty" **_Place_** itemtype (without any _properties_ or sub-itemtypes) is useless for machines, there is no content with the required markup to interpret. So the machines will ignore the microdata (validation error).

Fifth:
This brings me to Google: As already mentioned it is required to have a name and an address (at least the city) for the location of an event, otherwise the hole event entry will be ignored by Google and the event will not show up in search results as rich snippet. Missing markup will also bring up validation errors in the [microdata testing tool](https://search.google.com/structured-data/testing-tool), as mentioned in the original issue. In case both (location name and city) are given, the event will show up in the search results:

example1

The city is also used for the **knowledge graph** by Google. So if you search for like "Wuppertal events" a list with different events will be presented, collected on different websites. This is only possible when the city is marked up in the microdata. The following screenshot is taken by google.com, I have seen this knowledge graph in other languages like on google.de as well sometimes:

example2

So what can we do?

You wrote: 

> The "location" field in the events module can be anything (a name, an address, a description etc.)

...yeah, that's a problem. So we should **not** add the microdata for this field by default, because the current field could contain "wrong" data (wrong in case of microdata: anything other than a name for the location).

A possible solution could be: Add the new field for the city. Then for the output: When the city field is empty, no microdata markup for the location will be added at all (the event will not show up in Google search results). So something like this:

if ( empty(city) ) { output **without** microdata } else [ output **with** microdata for location }

Would that be a compromise?

When current Contao users are just updating nothing will change for them. Only when they start filling the new city field, the microdata output for location will be added. (The current field should still be renamed to make the difference/new function clearer).

What do you think?

**Comment by CMSworker** [comment]
I changed the template in pr #18 as proposed (show microdata for location only in case a city is present).

@contao/developers : just asking for some feedback and opinions, thanks. Related issue: #12

Also adding @kmielke as he made the _calendar_extended_ extension. In case the microdata is not ment to be added to the core, maybe we can add the microdata support in the extension? (still think it should be added correctly in the core)

**Comment by leofeyer** [comment]
@ausi /cc

**Comment by ausi** [comment]
> So name is also a valid property to describe a Place, because a Place is a Thing.

Correct. Looks like the „Thing“ attributes were missing on <http://schema.org/Place> and were added on 12th Oct., see [2017-10-11](https://web.archive.org/web/20171011105732/http://schema.org/Place) vs [2017-10-12](https://web.archive.org/web/20171012105920/http://schema.org/Place).

So I think `itemprop="location" itemscope itemtype="http://schema.org/Place"> <span itemprop="name">` is correct.

> The "location" field in the events module can be anything (a name, an address, a description etc.)

I think mostly everything of what can go into a location field is also a valid „name“ for a „Place“. So I think we can always add this microdata.

If we want to add a location city field should be discussed in #18

**Review by ausi — APPROVED** [review]

**Comment by leofeyer** [comment]
See #18.

**Pull request closed without merging**
