### PR TITLE
add download attribute to download elements

### PR DESCRIPTION
**Pull request by frontendschlampe**
prevent errors like:
Resource interpreted as Document but transferred with MIME type application/pdf: "*?file=*.pdf". (Chrome) or [Error] Failed to load resource: Das Laden des Frames wurde unterbrochen (*, line 0) *?file=*.pdf (Safari)
see more https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a#attr-download

### CODE REVIEW

**Comment by frontendschlampe** [comment]
should be included to Contao 4.4, 4.5 and future versions

**Comment by leofeyer** [comment]
> should be included to Contao 4.4, 4.5 and future versions

Then you should target your pull request against the `4.4` branch. 😉

**Comment by frontendschlampe** [comment]
should I really? additional or only to `4.4` Branch?

**Comment by leofeyer** [comment]
If it is a bug fix that applies to Contao 4.4, you should target your pull request against the `4.4` branch. The changes will then be merged into the `4.5` and the `master` branch automatically.

If it is a new feature for Contao 4.6, you should target your pull request against the `master` branch.

See: https://contao.org/de/news/wechsel-von-gitflow-zu-trunk-based-development.html

**Comment by frontendschlampe** [comment]
ah yes ... I will do so

**Comment by frontendschlampe** [comment]
I changed all bases

**Comment by leofeyer** [comment]
See contao/core-bundle#1336.

**Pull request closed without merging**
