### PR TITLE
add dcaPicker to url field

### PR DESCRIPTION
**Pull request by fritzmg**
Same as https://github.com/contao/news-bundle/pull/16

### CODE REVIEW

**Review by aschempp — COMMENTED** [review]
I think you don't need to set the options as they are the default and there's no configuration for link picker.

**Comment by fritzmg** [comment]
Which options do you mean exactly?

**Comment by fritzmg** [comment]
Ah, you mean
```php
'fieldType'=>'radio', 'filesOnly'=>true
```
Indeed, those are not necessary. I copied them from `tl_content.url`, see https://github.com/contao/core-bundle/blob/4.4.2/src/Resources/contao/dca/tl_content.php#L468

Should I remove them or leave them to stay consistent with the `core-bundle`? Or should they be removed in the `core-bundle` for the `url` and `imageUrl` fields as well?

Same story with the `tl_news.imageUrl` and `tl_calendar_events.imageUrl` field, see https://github.com/contao/calendar-bundle/blob/4.4.2/src/Resources/contao/dca/tl_calendar_events.php#L350 for example.

**Comment by aschempp** [comment]
I would remove it everywhere. They probably became obsolete with the fixed picker implementation.

**Comment by fritzmg** [comment]
PRs updated.

**Comment by leofeyer** [comment]
Will contao/core-bundle#1171 render this PR redundant?

**Comment by aschempp** [comment]
> Will #1171 render this PR redundant?

No. This PR is about enabling the picker on a field, https://github.com/contao/core-bundle/pull/1171 is about adding a universal picker widget.

**Comment by leofeyer** [comment]
So now we don't actually need the "Page" and "Article" options anymore, because the picker also allows to pick those.



So I would change the options to "Use default" and "Custom target", ok?

**Comment by fritzmg** [comment]
Good point. Should we be concerned about a backwards compatibility break here though? Someone might check for `->source == 'internal'` etc. in a hook, template or module.

**Comment by leofeyer** [comment]
Good point. We are doing it ourselves:

https://github.com/contao/calendar-bundle/blob/5f4510f488323847da2ba0b30e9304c35d45dc5e/src/Resources/contao/dca/tl_calendar_events.php#L796-L831

So we cannot remove the options.

**Comment by fritzmg** [comment]
May be the translation should be renamed though from _External URL_ to something more general. Like _Custom_ or _Other_.

**Pull request merged**
